"""added new column in the db

Revision ID: 2f4afa20072c
Revises: 76a0adef5ccb
Create Date: 2021-07-26 18:56:35.306057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4afa20072c'
down_revision = '76a0adef5ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('bread', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'bread')
    # ### end Alembic commands ###
